### ISSUE TITLE
[Feature Request] request info from goodreads.com to auto-populate title,desc,tags,image

### ISSUE THREAD

**Issue by gchingon** [dewey/WhatBookUpload#2]
have WhatBookUpload search goodreads based on Torrentfile:filename toauto populate title, tags, image, desc and ask user to approve <all> or individual fields and then submit. This would help streamline multiple file uploads (100>)

**Comment by dewey** [comment]
I won't be adding any new features as it was just a small project to play around with Python and not really maintained any more.
